language: R
cache: packages
sudo: false
warnings_are_errors: true

r:
  - release
  - devel
os:
  - linux
  - osx

r_packages:
  - covr
  - testthat
  - lintr

addons:
  apt:
    update: true

after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'

env:
  global:
    - PKG_CFLAGS="-Wall -pedantic"
