// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// method forward declarations
RcppExport SEXP _lazyvec_lazy_vec();

static const R_CallMethodDef CallEntries[] = {
    {"_lazyvec_rcpp_hello_world", (DL_FUNC) &_lazyvec_lazy_vec, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_lazyvec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
