// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lazy_vec_construct
SEXP lazy_vec_construct(SEXP lazyvec_interface);
RcppExport SEXP _lazyvec_lazy_vec_construct(SEXP lazyvec_interfaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lazyvec_interface(lazyvec_interfaceSEXP);
    rcpp_result_gen = Rcpp::wrap(lazy_vec_construct(lazyvec_interface));
    return rcpp_result_gen;
END_RCPP
}
