# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

construct_altrep_integer_wrapper <- function(data) {
    .Call(`_lazyvec_construct_altrep_integer_wrapper`, data)
}

is_altrep_vector <- function(vec) {
    .Call(`_lazyvec_is_altrep_vector`, vec)
}

