# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altrep_full_class <- function(altrep_vec) {
    .Call(`_lazyvec_altrep_full_class`, altrep_vec)
}

trigger_length <- function(x) {
    .Call(`_lazyvec_trigger_length`, x)
}

trigger_duplicate_ex <- function(x, deep) {
    .Call(`_lazyvec_trigger_duplicate_ex`, x, deep)
}

trigger_serialized_state <- function(x) {
    .Call(`_lazyvec_trigger_serialized_state`, x)
}

trigger_dataptr_or_null <- function(x) {
    .Call(`_lazyvec_trigger_dataptr_or_null`, x)
}

trigger_get_region <- function(x, pos, size) {
    .Call(`_lazyvec_trigger_get_region`, x, pos, size)
}

trigger_element <- function(x, pos) {
    .Call(`_lazyvec_trigger_element`, x, pos)
}

trigger_is_sorted <- function(x) {
    .Call(`_lazyvec_trigger_is_sorted`, x)
}

trigger_no_na <- function(x) {
    .Call(`_lazyvec_trigger_no_na`, x)
}

trigger_sum <- function(x, na_rm) {
    .Call(`_lazyvec_trigger_sum`, x, na_rm)
}

trigger_min <- function(x, na_rm) {
    .Call(`_lazyvec_trigger_min`, x, na_rm)
}

trigger_max <- function(x, na_rm) {
    .Call(`_lazyvec_trigger_max`, x, na_rm)
}

trigger_unserialize_ex <- function(info, state, attr, objf, levs) {
    .Call(`_lazyvec_trigger_unserialize_ex`, info, state, attr, objf, levs)
}

trigger_inspect <- function(x, pre, deep, pvec) {
    invisible(.Call(`_lazyvec_trigger_inspect`, x, pre, deep, pvec))
}

trigger_coerce <- function(x, type) {
    .Call(`_lazyvec_trigger_coerce`, x, type)
}

altrep_integer_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_integer_wrapper`, data)
}

altrep_logical_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_logical_wrapper`, data)
}

altrep_raw_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_raw_wrapper`, data)
}

altrep_real_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_real_wrapper`, data)
}

altrep_string_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_string_wrapper`, data)
}

is_altrep_vector <- function(vec) {
    .Call(`_lazyvec_is_altrep_vector`, vec)
}

altrep_class <- function(vec) {
    .Call(`_lazyvec_altrep_class`, vec)
}

lazyvec_integer_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_integer_wrapper`, data)
}

lazyvec_logical_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_logical_wrapper`, data)
}

lazyvec_raw_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_raw_wrapper`, data)
}

lazyvec_real_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_real_wrapper`, data)
}

lazyvec_string_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_string_wrapper`, data)
}

