# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altrep_full_class <- function(altrep_vec) {
    .Call(`_lazyvec_altrep_full_class`, altrep_vec)
}

altrep_length_method <- function(x) {
    .Call(`_lazyvec_altrep_length_method`, x)
}

altrep_duplicate_ex_method <- function(x, deep) {
    .Call(`_lazyvec_altrep_duplicate_ex_method`, x, deep)
}

altrep_serialized_state_method <- function(x) {
    .Call(`_lazyvec_altrep_serialized_state_method`, x)
}

#' Trigger ALTREP_INSPECT method
#' 
#' @param x is the object to inspect
#' @param pre is the prefix
#' @param deep specifies the recursion behavior (0 = no recursion, -1 = [sort of] unlimited
#'   recursion, positive numbers define the maximum recursion depth)
#' @param pvec is the maximum number of vector elements to show
altrep_inspect_method <- function(x, pre, deep, pvec) {
    invisible(.Call(`_lazyvec_altrep_inspect_method`, x, pre, deep, pvec))
}

altrep_coerce_method <- function(x, type) {
    .Call(`_lazyvec_altrep_coerce_method`, x, type)
}

altrep_integer_Elt_method <- function(x, i) {
    .Call(`_lazyvec_altrep_integer_Elt_method`, x, i)
}

altrep_integer_is_sorted_method <- function(x) {
    .Call(`_lazyvec_altrep_integer_is_sorted_method`, x)
}

altrep_integer_no_na_method <- function(x) {
    .Call(`_lazyvec_altrep_integer_no_na_method`, x)
}

altrep_integer_sum_method <- function(x, na_rm) {
    .Call(`_lazyvec_altrep_integer_sum_method`, x, na_rm)
}

altrep_integer_min_method <- function(x, na_rm) {
    .Call(`_lazyvec_altrep_integer_min_method`, x, na_rm)
}

altrep_integer_max_method <- function(x, na_rm) {
    .Call(`_lazyvec_altrep_integer_max_method`, x, na_rm)
}

altrep_integer_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_integer_wrapper`, data)
}

altrep_logical_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_logical_wrapper`, data)
}

altrep_raw_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_raw_wrapper`, data)
}

altrep_real_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_real_wrapper`, data)
}

altrep_string_wrapper <- function(data) {
    .Call(`_lazyvec_altrep_string_wrapper`, data)
}

is_altrep_vector <- function(vec) {
    .Call(`_lazyvec_is_altrep_vector`, vec)
}

altrep_class <- function(vec) {
    .Call(`_lazyvec_altrep_class`, vec)
}

lazyvec_integer_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_integer_wrapper`, data)
}

lazyvec_logical_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_logical_wrapper`, data)
}

lazyvec_raw_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_raw_wrapper`, data)
}

lazyvec_real_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_real_wrapper`, data)
}

lazyvec_string_wrapper <- function(data) {
    .Call(`_lazyvec_lazyvec_string_wrapper`, data)
}

